### ISSUE TITLE
Tests fail if FinSetsForCAP is present

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/ZariskiFrames#22]
`FinSetsForCAP` is an optional dependency of `FreydCategoriesForCAP`. If it is present
```
#I  method installed for IsInjective matches more than one declaration
```
is printed when loading `FreydCategoriesForCAP`, if it is not present, no such warning is printed. Thus, it is hard to make the tests work in both cases. `ZariskiFrames` does not clone `FinSetsForCAP` in the CI, so the tests succeed there. On the other hand, `Toposes` clones `FinSetsForCAP` in the CI, so the CI currently fails: https://github.com/homalg-project/Toposes/actions/runs/681374188

I'm not sure what the best solution is. Note that the issue will vanish in the context of https://github.com/homalg-project/CAP_project/pull/649 anyway.

In any case, there is a version of the file `050_LoadPackage.tst` at the top level, which should not be there.

**Comment by mohamed-barakat** [comment]
I made two mistakes in the last commit.
1. The top-level `050_LoadPackage.tst` should have been moved to the subdirectory `tst/`.
2. `FinSetForCAP` should have been added to the list of repositories to clone.

Thanks for opening an issue. Once the problem vanishes, I will simply delete the `050_LoadPackage.tst` from all packages.

What is annoying is that I didn't get the notification of failure:

https://github.com/homalg-project/Toposes/actions/runs/681374188

**Comment by zickgraf** [comment]
> What is annoying is that I didn't get the notification of failure

That's weird, me neither, I was looking at `Toposes` by chance and noticed that the CI is red. Just a week ago I got a notification, so this seems to be a problem on GitHub's side.
